# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventan_verduras.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_verduras(object):
    def setupUi(self, ventana_verduras):
        ventana_verduras.setObjectName("ventana_verduras")
        ventana_verduras.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ventana_verduras)
        self.centralwidget.setObjectName("centralwidget")
        ventana_verduras.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ventana_verduras)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        ventana_verduras.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ventana_verduras)
        self.statusbar.setObjectName("statusbar")
        ventana_verduras.setStatusBar(self.statusbar)

        self.retranslateUi(ventana_verduras)
        QtCore.QMetaObject.connectSlotsByName(ventana_verduras)

    def retranslateUi(self, ventana_verduras):
        _translate = QtCore.QCoreApplication.translate
        ventana_verduras.setWindowTitle(_translate("ventana_verduras", "MainWindow"))
